export enum CronStatuses {
    UNKNOWN_ERROR = -1,
    SUCCESS = 0,
    VK_BOT_POLLING_ERROR = 1000,
    VK_BOT_SEND_MESSAGE_ERROR = 1001,
    VK_TASK_EXEC_ERROR = 2001,
    VK_FETCH_CHECK_TODAY_CONTRIBUTES_ERROR = 3002,
}